' convert it with additional command line argument -DRELATIVE_INCLUDE="relative/absolute" to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include ./C4_Context.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!endif

' Scope: A single software system.
' Primary elements: Containers within the software system in scope.
' Supporting elements: People and software systems directly connected to the containers.
' Intended audience: Technical people inside and outside of the software development team; including software architects, developers and operations/support staff.

' Colors
' ##################################

!$CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$CONTAINER_BG_COLOR ?= "#438DD5"
!$CONTAINER_BORDER_COLOR ?= "#3C7FC0"

!$CONTAINER_BOUNDARY_COLOR ?= $BOUNDARY_COLOR
!$CONTAINER_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$CONTAINER_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR
!$EXTERNAL_CONTAINER_BG_COLOR ?= "#B3B3B3"
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= "#A6A6A6"

' Labels
' ##################################

!$CONTAINER_LEGEND_TEXT ?= "container"
!$CONTAINER_BOUNDARY_TYPE ?= "container"
!$CONTAINER_BOUNDARY_LEGEND_TEXT ?= "container boundary"
!$EXTERNAL_CONTAINER_LEGEND_TEXT ?= "external container"

' Styling
' ##################################О компании
Микросервисная архитектура способна решать специфические задачи и в аграрной сфере (AgTech): от точного земледелия и управления техникой до отслеживания цепочек поставок и анализа данных.
Компания «АгроТех Х» давно работает на рынке, занимается выращиванием различных культур, имеет 150 тепличных комплексов по всей стране и занимается свиноводством. У компании есть свой собственный парк техники.
IT-ландшафт компании формировался постепенно, и там можно встретить как достаточно современные, так и совсем устаревшие технологии, от которых постепенно отказываются.
По мере развития IoT компания пробует различные датчики и системы в своей работе. Например, для парка техники внедрён мониторинг местоположения, состояния, расхода топлива, выполнения работ множества единиц техники (тракторы, комбайны, опрыскиватели) разных производителей для планирования заданий, сокращения издержек и повышения производительности.
Сейчас перед компанией стоит задача — повысить эффективность в сфере животноводства и по максимуму автоматизировать процессы, связанные с кормлением, безопасностью и мониторингом поголовья скота. 
На рынке уже представлены продукты из этой сферы: это PigVision, ALUS или PigTales, есть различные исследования и проекты: https://blog.iotcloudplatform.com/how-to-design-an-iot-smart-pig-farming-system/ . Но купить и адаптировать их в настоящих реалиях не получится либо из-за ограничений в законодательстве, либо из-за дороговизны реализации. Например, использование дронов для мониторинга скота.
Поэтому решено сделать MVP архитектуры c нуля и запустить как отдельную платформу для мониторинга скота. Сначала планируется реализовать это на ограниченном количестве ферм, а затем потенциально предлагать как SaaS-решение для других компаний — это уже выходит за рамки проектной работы.
Функциональные требования к системе
Система должна:
фиксировать признаки беспокойного поведения или драк среди животных и оповещать оператора;
фиксировать признаки задавливания поросят;
управлять кормушками и поилками разных производителей;
оценивать состояние животных по внешнему виду и поведению: болезнь, гибель, беспокойство и так далее;
следить за состоянием систем фильтрации воды;
пересчитывать поголовье;
следить за запасами еды и прогнозировать расход;
поддерживать необходимое количество видеокамер для аналитики в реальном времени от разных производителей;
быть построена по принципу «центральный сервер — агенты» на конкретных фермах без ограничения количества таких агентов (в синхронизации между агентами и центральным сервером допускается задержка до 10 минут без учёта проблем со связью);
предоставлять базовые метрики для передачи в другие системы;
поддерживать возможность добавления собственных метрик;
работать даже в случае отсутствия интернета и при необходимости отправлять уведомления дежурному сотруднику на местах мониторинга, а после восстановления связи синхронизироваться с центральной системой;
иметь разделение ролей и поддерживать современные способы аутентификации и авторизации;
иметь API для создания мобильного приложения или веб-приложения.
Нефункциональные требования
Система должна:
обеспечивать достаточно высокую отказоустойчивость 99,95%;
быть расширяемой, то есть иметь возможность разработать новый функционал без изменений существующего;
иметь высокую производительность — от момента возникновения нештатной ситуации, зафиксированной с помощью видеоаналитики, должно проходить не более 5 секунд до момента оповещения;
позволять системе видеоаналитики реагировать в реальном времени (миллисекунды).
Что нужно учесть
Нейронные сети
Часто нейронные сети путают тень животного с самим животным — для MVP не критично.
Проблемы с освещением — камеры должны уметь снимать и в ночное время суток.
Трекинг животных достаточно сложен, так как особи очень похожи.
Готовую нейросетевую модель предоставят партнёры.
Инфраструктура:
На ферме нестабильный WiFi, поэтому нужно продумать альтернативные каналы связи.
Покрытие камерами всей площади — нужно по максимуму убрать слепые зоны либо воспользоваться камерами типа «рыбий глаз», но это снизит качество в силу выпуклости линзы.
На каждой ферме допустимо использовать один центральный сервер и необходимый набор edge-устройств.О компании
Микросервисная архитектура способна решать специфические задачи и в аграрной сфере (AgTech): от точного земледелия и управления техникой до отслеживания цепочек поставок и анализа данных.
Компания «АгроТех Х» давно работает на рынке, занимается выращиванием различных культур, имеет 150 тепличных комплексов по всей стране и занимается свиноводством. У компании есть свой собственный парк техники.
IT-ландшафт компании формировался постепенно, и там можно встретить как достаточно современные, так и совсем устаревшие технологии, от которых постепенно отказываются.
По мере развития IoT компания пробует различные датчики и системы в своей работе. Например, для парка техники внедрён мониторинг местоположения, состояния, расхода топлива, выполнения работ множества единиц техники (тракторы, комбайны, опрыскиватели) разных производителей для планирования заданий, сокращения издержек и повышения производительности.
Сейчас перед компанией стоит задача — повысить эффективность в сфере животноводства и по максимуму автоматизировать процессы, связанные с кормлением, безопасностью и мониторингом поголовья скота. 
На рынке уже представлены продукты из этой сферы: это PigVision, ALUS или PigTales, есть различные исследования и проекты: https://blog.iotcloudplatform.com/how-to-design-an-iot-smart-pig-farming-system/ . Но купить и адаптировать их в настоящих реалиях не получится либо из-за ограничений в законодательстве, либо из-за дороговизны реализации. Например, использование дронов для мониторинга скота.
Поэтому решено сделать MVP архитектуры c нуля и запустить как отдельную платформу для мониторинга скота. Сначала планируется реализовать это на ограниченном количестве ферм, а затем потенциально предлагать как SaaS-решение для других компаний — это уже выходит за рамки проектной работы.
Функциональные требования к системе
Система должна:
фиксировать признаки беспокойного поведения или драк среди животных и оповещать оператора;
фиксировать признаки задавливания поросят;
управлять кормушками и поилками разных производителей;
оценивать состояние животных по внешнему виду и поведению: болезнь, гибель, беспокойство и так далее;
следить за состоянием систем фильтрации воды;
пересчитывать поголовье;
следить за запасами еды и прогнозировать расход;
поддерживать необходимое количество видеокамер для аналитики в реальном времени от разных производителей;
быть построена по принципу «центральный сервер — агенты» на конкретных фермах без ограничения количества таких агентов (в синхронизации между агентами и центральным сервером допускается задержка до 10 минут без учёта проблем со связью);
предоставлять базовые метрики для передачи в другие системы;
поддерживать возможность добавления собственных метрик;
работать даже в случае отсутствия интернета и при необходимости отправлять уведомления дежурному сотруднику на местах мониторинга, а после восстановления связи синхронизироваться с центральной системой;
иметь разделение ролей и поддерживать современные способы аутентификации и авторизации;
иметь API для создания мобильного приложения или веб-приложения.
Нефункциональные требования
Система должна:
обеспечивать достаточно высокую отказоустойчивость 99,95%;
быть расширяемой, то есть иметь возможность разработать новый функционал без изменений существующего;
иметь высокую производительность — от момента возникновения нештатной ситуации, зафиксированной с помощью видеоаналитики, должно проходить не более 5 секунд до момента оповещения;
позволять системе видеоаналитики реагировать в реальном времени (миллисекунды).
Что нужно учесть
Нейронные сети
Часто нейронные сети путают тень животного с самим животным — для MVP не критично.
Проблемы с освещением — камеры должны уметь снимать и в ночное время суток.
Трекинг животных достаточно сложен, так как особи очень похожи.
Готовую нейросетевую модель предоставят партнёры.
Инфраструктура:
На ферме нестабильный WiFi, поэтому нужно продумать альтернативные каналы связи.
Покрытие камерами всей площади — нужно по максимуму убрать слепые зоны либо воспользоваться камерами типа «рыбий глаз», но это снизит качество в силу выпуклости линзы.
На каждой ферме допустимо использовать один центральный сервер и необходимый набор edge-устройств.О компании
Микросервисная архитектура способна решать специфические задачи и в аграрной сфере (AgTech): от точного земледелия и управления техникой до отслеживания цепочек поставок и анализа данных.
Компания «АгроТех Х» давно работает на рынке, занимается выращиванием различных культур, имеет 150 тепличных комплексов по всей стране и занимается свиноводством. У компании есть свой собственный парк техники.
IT-ландшафт компании формировался постепенно, и там можно встретить как достаточно современные, так и совсем устаревшие технологии, от которых постепенно отказываются.
По мере развития IoT компания пробует различные датчики и системы в своей работе. Например, для парка техники внедрён мониторинг местоположения, состояния, расхода топлива, выполнения работ множества единиц техники (тракторы, комбайны, опрыскиватели) разных производителей для планирования заданий, сокращения издержек и повышения производительности.
Сейчас перед компанией стоит задача — повысить эффективность в сфере животноводства и по максимуму автоматизировать процессы, связанные с кормлением, безопасностью и мониторингом поголовья скота. 
На рынке уже представлены продукты из этой сферы: это PigVision, ALUS или PigTales, есть различные исследования и проекты: https://blog.iotcloudplatform.com/how-to-design-an-iot-smart-pig-farming-system/ . Но купить и адаптировать их в настоящих реалиях не получится либо из-за ограничений в законодательстве, либо из-за дороговизны реализации. Например, использование дронов для мониторинга скота.
Поэтому решено сделать MVP архитектуры c нуля и запустить как отдельную платформу для мониторинга скота. Сначала планируется реализовать это на ограниченном количестве ферм, а затем потенциально предлагать как SaaS-решение для других компаний — это уже выходит за рамки проектной работы.
Функциональные требования к системе
Система должна:
фиксировать признаки беспокойного поведения или драк среди животных и оповещать оператора;
фиксировать признаки задавливания поросят;
управлять кормушками и поилками разных производителей;
оценивать состояние животных по внешнему виду и поведению: болезнь, гибель, беспокойство и так далее;
следить за состоянием систем фильтрации воды;
пересчитывать поголовье;
следить за запасами еды и прогнозировать расход;
поддерживать необходимое количество видеокамер для аналитики в реальном времени от разных производителей;
быть построена по принципу «центральный сервер — агенты» на конкретных фермах без ограничения количества таких агентов (в синхронизации между агентами и центральным сервером допускается задержка до 10 минут без учёта проблем со связью);
предоставлять базовые метрики для передачи в другие системы;
поддерживать возможность добавления собственных метрик;
работать даже в случае отсутствия интернета и при необходимости отправлять уведомления дежурному сотруднику на местах мониторинга, а после восстановления связи синхронизироваться с центральной системой;
иметь разделение ролей и поддерживать современные способы аутентификации и авторизации;
иметь API для создания мобильного приложения или веб-приложения.
Нефункциональные требования
Система должна:
обеспечивать достаточно высокую отказоустойчивость 99,95%;
быть расширяемой, то есть иметь возможность разработать новый функционал без изменений существующего;
иметь высокую производительность — от момента возникновения нештатной ситуации, зафиксированной с помощью видеоаналитики, должно проходить не более 5 секунд до момента оповещения;
позволять системе видеоаналитики реагировать в реальном времени (миллисекунды).
Что нужно учесть
Нейронные сети
Часто нейронные сети путают тень животного с самим животным — для MVP не критично.
Проблемы с освещением — камеры должны уметь снимать и в ночное время суток.
Трекинг животных достаточно сложен, так как особи очень похожи.
Готовую нейросетевую модель предоставят партнёры.
Инфраструктура:
На ферме нестабильный WiFi, поэтому нужно продумать альтернативные каналы связи.
Покрытие камерами всей площади — нужно по максимуму убрать слепые зоны либо воспользоваться камерами типа «рыбий глаз», но это снизит качество в силу выпуклости линзы.
На каждой ферме допустимо использовать один центральный сервер и необходимый набор edge-устройств.
UpdateElementStyle("container", $CONTAINER_BG_COLOR, $CONTAINER_FONT_COLOR, $CONTAINER_BORDER_COLOR, $shape=$DEFAULT_SHAPE, $legendText="$CONTAINER_LEGEND_TEXT")
UpdateElementStyle("external_container", $EXTERNAL_CONTAINER_BG_COLOR, $EXTERNAL_CONTAINER_FONT_COLOR, $EXTERNAL_CONTAINER_BORDER_COLOR, $shape=$DEFAULT_SHAPE, $legendText="$EXTERNAL_CONTAINER_LEGEND_TEXT")

UpdateBoundaryStyle("container", $bgColor=$CONTAINER_BOUNDARY_BG_COLOR, $fontColor=$CONTAINER_BOUNDARY_COLOR, $borderColor=$CONTAINER_BOUNDARY_COLOR, $type="$CONTAINER_BOUNDARY_TYPE", $shape=$DEFAULT_SHAPE, $legendText="$CONTAINER_BOUNDARY_LEGEND_TEXT")

' shortcuts with default colors
!unquoted procedure AddContainerTag($tagStereo, $bgColor="", $fontColor="", $borderColor="", $shadowing="", $shape="", $sprite="", $techn="", $legendText="", $legendSprite="", $borderStyle="", $borderThickness="")
  $addElementTagInclReuse("container", $tagStereo, $bgColor, $fontColor, $borderColor, $shadowing, $shape, $sprite, $techn, $legendText, $legendSprite, $borderStyle, $borderThickness)
!endprocedure
!unquoted procedure AddExternalContainerTag($tagStereo, $bgColor="", $fontColor="", $borderColor="", $shadowing="", $shape="", $sprite="", $techn="", $legendText="", $legendSprite="", $borderStyle="", $borderThickness="")
  $addElementTagInclReuse("external_container", $tagStereo, $bgColor, $fontColor, $borderColor, $shadowing, $shape, $sprite, $techn, $legendText, $legendSprite, $borderStyle, $borderThickness)
!endprocedure

!unquoted procedure UpdateContainerBoundaryStyle($bgColor=$CONTAINER_BOUNDARY_BG_COLOR, $fontColor=$CONTAINER_BOUNDARY_COLOR, $borderColor=$CONTAINER_BOUNDARY_COLOR, $shadowing="", $shape="", $type="Container", $legendText="", $borderStyle="", $borderThickness="", $sprite="", $legendSprite="")
  UpdateBoundaryStyle("container", $bgColor, $fontColor, $borderColor, $shadowing, $shape, $type, $legendText, $borderStyle, $borderThickness, $sprite, $legendSprite)
!endprocedure

' Layout
' ##################################

SetDefaultLegendEntries("person\nsystem\ncontainer\nexternal_person\nexternal_system\nexternal_container\nenterprise_boundary\nsystem_boundary\ncontainer_boundary\nboundary")

!procedure LAYOUT_WITH_LEGEND()
hide stereotype
legend right
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
|<$PERSON_BG_COLOR> person |
|<$SYSTEM_BG_COLOR> system |
|<$CONTAINER_BG_COLOR> container |
|<$EXTERNAL_PERSON_BG_COLOR> external person |
|<$EXTERNAL_SYSTEM_BG_COLOR> external system |
|<$EXTERNAL_CONTAINER_BG_COLOR> external container |
endlegend
!endprocedure

' Elements
' ##################################

!unquoted procedure Container($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="", $baseShape="rectangle")
  $getElementLine($baseShape , "container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure ContainerDb($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  $getElementLine("database", "container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure ContainerQueue($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  $getElementLine("queue", "container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure Container_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="", $baseShape="rectangle")
  $getElementLine($baseShape , "external_container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure ContainerDb_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  $getElementLine("database", "external_container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure ContainerQueue_Ext($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  $getElementLine("queue", "external_container", $alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

' Boundaries
' ##################################

!unquoted procedure Container_Boundary($alias, $label, $tags="", $link="", $descr = "")
  !if ($tags != "")
    !$allTags = $tags + '+container'
  !else
    !$allTags = 'container'
  !endif
  ' $type defined via $tag style
  Boundary($alias, $label, "", $allTags, $link, $descr)
!endprocedure
